name: build binary

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: chmod +x pre_install_linux_all.sh && sudo ./pre_install_linux_all.sh all
    - name: make server
      run: make server-ext
    - name: make client
      run: make client
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v6.0.0
      with:
        name: dist-files
        path: dist
